[book]
title = "KIP Technical Primer"
description = "Experimental representation of KIP's Technical Primer"
authors = ["KIP Foundation"]
multilingual = false
src = "src"

[output.html]
mathjax-support = true

[output.html.playpen]
editable = false

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2